FROM node:24.13.0 as build

WORKDIR /app

COPY package.json ./
RUN npm i

COPY . . /app/

RUN npm run build

FROM nginx:1.28

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./default.conf /etc.nginx/conf.d/defaul.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]