apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  # 1. 오타 수정: persistentVolumeReclaimPolicy (소문자 p 시작, Reclaim 포함)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/class/study39/html
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: # 2. 오타 수정: matchExpressions (복수형)
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop